### ISSUE TITLE
Can't open file

### ISSUE THREAD

**Issue by rlaurente** [mostafa-mansour1/previewAnyFile#1]
Hi there

I'm having this error in android 
err file:///storage/emulated/0/Download/test.docx exposed beyond app through Intent.getData()

Do you have idea how to fix this ?

**Comment by mostafa-mansour1** [comment]
Can you tell me how to reproduce to debug it?

**Comment by rlaurente** [comment]
I just installed it with latest ionic.
It works if I set target sdk to 23. The error occurs in target sdk >= 24.

I think it's related to this.
https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed

**Comment by mostafa-mansour1** [comment]
Let me do the fix and commit it , thanks for reporting the issue

**Comment by danillosantos** [comment]
The same scenario is happening here :(

When I get the time I'll take a look at this.

**Comment by mostafa-mansour1** [comment]
me too

**Comment by EOussama** [comment]
Any fixes to this?

**Comment by mostafa-mansour1** [comment]
still work in it, try to fix this weekend

**Comment by EOussama** [comment]
> still work in it, try to fix this weekend

Thank you for caring, much love ♥

**Comment by mostafa-mansour1** [comment]
this issue is fixed, kindly use the latest version 0.1.5
