### ISSUE TITLE
[FIXED] Preview File from assets folder

### ISSUE THREAD

**Issue by andreiradoi** [mostafa-mansour1/previewAnyFile#10]
Hi,

Using Ionic 4, how would a path for a file located in /assets directory look like?

I've tried using: 
 - file://assets/filename.pdf
-  file.applicationDirectory + '/public/assets/filename.pdf' (ionic-native file plugin)

But I am getting 'The requested URL was not found on this server.'

I've checked my simulator directory and the file is there.

Thanks

**Comment by mostafa-mansour1** [comment]
Try relative directly
I already did this , but I am on my way i will give you proper answer tomorrow

But for now try relative path ‘/assets/file.pdf’


Regards,
___________________________
Mostafa Mansour
Software Engineer
00971 524988466
0020 1113019196

On 27 Aug 2020, at 5:49 PM, andreiradoi <notifications@github.com> wrote:

﻿

Hi,

Using Ionic 4, how would a path for a file located in /assets directory look like?

I've tried using:

  *   file://assets/filename.pdf
  *   file.applicationDirectory + '/public/assets/filename.pdf' (ionic-native file plugin)

But I am getting 'The requested URL was not found on this server.'

I've checked my simulator directory and the file is there.

Thanks

**Comment by andreiradoi** [comment]
"unsupported URL" for any urls that don't have file://

I am using an iPad Simulator with iOS 13.5 if it's any help.

Thanks a lot for your help!

**Comment by andreiradoi** [comment]
Hi Mostafa,

By any change, did you find the time to check out this issue?

Thanks,

**Comment by mostafa-mansour1** [comment]
the trick is to get the blob or base64 of the asset file 

check this code 

`
import { PreviewAnyFile } from '@ionic-native/preview-any-file/ngx';
import { File } from '@ionic-native/File/ngx';
import { HttpClient } from '@angular/common/http';
`

`constructor(
private http: HttpClient,
private file: File,
private previewAnyFile: PreviewAnyFile,)`

`    let assetPath = './assets/files/preview.pdf';
    this.http.get(assetPath, { responseType: 'blob' }).subscribe(fileBlob => {
      let fileName = assetPath.replace(/^.*(\\|\/|\:)/, '');
      const writeDirectory = this.platform.is('ios') ? this.file.syncedDataDirectory : this.file.externalDataDirectory;
      this.file.writeFile(writeDirectory, fileName, fileBlob, { replace: true }).then(fileProp => {
        this.filesService.previewExternalLink(fileProp.nativeURL)
      })
    });`

**Comment by andreiradoi** [comment]
Beautiful!

Thank you so much!

**Comment by mostafa-mansour1** [comment]
there is a new version from the plugin, in this version you can use the previewAsset method directly without any extra codes
