### ISSUE TITLE
iOS build fails with error: Value for SWIFT_VERSION cannot be empty 

### ISSUE THREAD

**Issue by July-** [mostafa-mansour1/previewAnyFile#12]
Without this plugin build is successful but when plugin is added, the following error occurs in Xcode: Value for SWIFT_VERSION cannot be empty. What could be done to fix that?

**Comment by mostafa-mansour1** [comment]
I will review and will update you


Regards,
___________________________
Mostafa Mansour
Software Engineer
00971 524988466
0020 1113019196

On 30 Jan 2021, at 12:25 AM, July- <notifications@github.com> wrote:

﻿

Without this plugin build is successful but when plugin is added, the following error occurs in Xcode: Value for SWIFT_VERSION cannot be empty. What could be done to fix that?

**Comment by July-** [comment]
Got it working by specifying Swift language version to 4 in Xcode (just selected randomly, there also were options 4.2 and 5). Thanks!

**Comment by mostafa-mansour1** [comment]
I think any version number more than 3 it will work



Regards,
___________________________
Mostafa Mansour
Software Engineer
00971 524988466
0020 1113019196

On 30 Jan 2021, at 1:19 AM, July- <notifications@github.com> wrote:

﻿

Got it working by specifying Swift language version to 4 in Xcode (just selected randomly, there also were options 4.2 and 5). Thanks!
