### ISSUE TITLE
Ionic Native Wrapper Update

### ISSUE THREAD

**Issue by Phil0xFF** [mostafa-mansour1/previewAnyFile#14]
Hey, first of all thank you very much for the nice update. 👍 
Could you update the ionic native wrapper aswell? I need the update to display files on my S3 storage.

**Comment by mostafa-mansour1** [comment]
I already update and make a pull request https://github.com/ionic-team/ionic-native/pull/3612
but still not merged 

temporary, you can replace the folder from the zip file 
[preview-any-file.zip](https://github.com/mostafa-mansour1/previewAnyFile/files/5912855/preview-any-file.zip)

**Comment by Phil0xFF** [comment]
Thank you very much, great work!
