### ISSUE TITLE
Capacitor cordova-plugin-androidx error

### ISSUE THREAD

**Issue by Phil0xFF** [mostafa-mansour1/previewAnyFile#15]
Hello, the latest update v0.2.0 apparently uses cordova-plugin-androidx on Android and I can no longer build my project on Android. iOS works very well.

This is my error if I try to build the code in AndroidStudio.
I don't think this is a specific problem with previewAnyFile, but maybe you have a solution for Capacitor functionality.

`> Task :app:processDebugManifest FAILED
/Users/****/Apps/my-app/android/app/src/main/AndroidManifest.xml:36:13-64 Error:
	Attribute provider#androidx.core.content.FileProvider@authorities value=(app.my-app.fileprovider) from AndroidManifest.xml:36:13-64
	is also present at [:capacitor-cordova-android-plugins] AndroidManifest.xml:17:13-60 value=(app.my-app.provider).
	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:34:9-42:20 to override.
/Users/****/Apps/my-app/android/app/src/main/AndroidManifest.xml:41:17-51 Error:
	Attribute meta-data#android.support.FILE_PROVIDER_PATHS@resource value=(@xml/file_paths) from AndroidManifest.xml:41:17-51
	is also present at [:capacitor-cordova-android-plugins] AndroidManifest.xml:22:17-54 value=(@xml/preview_paths).
	Suggestion: add 'tools:replace="android:resource"' to <meta-data> element at AndroidManifest.xml:39:13-41:64 to override.`

**Comment by mostafa-mansour1** [comment]
Let me install on capictor project and will update you


Regards,
___________________________
Mostafa Mansour
Software Engineer
00971 524988466
0020 1113019196

On 3 Feb 2021, at 5:28 PM, Phil <notifications@github.com> wrote:

﻿

Hello, the latest update v0.2.0 apparently uses cordova-plugin-androidx on Android and I can no longer build my project on Android. iOS works very well.

This is my error if I try to build the code in AndroidStudio.
I don't think this is a specific problem with previewAnyFile, but maybe you have a solution for Capacitor functionality.

**Comment by mostafa-mansour1** [comment]
I publish a new version to fix the issue with the capacitor, kindly check and update me
