### ISSUE TITLE
Build fail IOS with version 0.2.2

### ISSUE THREAD

**Issue by maartenheideman** [mostafa-mansour1/previewAnyFile#16]
My app fails to build after updating previewAnyFile from `0.1.6` to `0.2.2`. Any idea what is could be?
```
Undefined symbol: _kUTTagClassMIMEType
Undefined symbol: _kUTTagClassFilenameExtension
Undefined symbol: _UTTypeCreatePreferredIdentifierForTag
Undefined symbol: _UTTypeCopyPreferredTagWithClass
```
```
Undefined symbols for architecture arm64:
  "_kUTTagClassMIMEType", referenced from:
      CordovaPlugins.PreviewAnyFile.previewPath(_command: __C.CDVInvokedUrlCommand) -> () in PreviewAnyFile.o
      CordovaPlugins.PreviewAnyFile.previewBase64(_command: __C.CDVInvokedUrlCommand) -> () in PreviewAnyFile.o
  "_kUTTagClassFilenameExtension", referenced from:
      CordovaPlugins.PreviewAnyFile.previewPath(_command: __C.CDVInvokedUrlCommand) -> () in PreviewAnyFile.o
      CordovaPlugins.PreviewAnyFile.previewBase64(_command: __C.CDVInvokedUrlCommand) -> () in PreviewAnyFile.o
  "_UTTypeCreatePreferredIdentifierForTag", referenced from:
      CordovaPlugins.PreviewAnyFile.previewPath(_command: __C.CDVInvokedUrlCommand) -> () in PreviewAnyFile.o
      CordovaPlugins.PreviewAnyFile.previewBase64(_command: __C.CDVInvokedUrlCommand) -> () in PreviewAnyFile.o
  "_UTTypeCopyPreferredTagWithClass", referenced from:
      CordovaPlugins.PreviewAnyFile.previewPath(_command: __C.CDVInvokedUrlCommand) -> () in PreviewAnyFile.o
      CordovaPlugins.PreviewAnyFile.previewBase64(_command: __C.CDVInvokedUrlCommand) -> () in PreviewAnyFile.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mostafa-mansour1** [comment]
I think something cached in your system 

can you try this solution?

https://stackoverflow.com/a/42063043/1002042 

Press "Cmmand+Shift+K" to clean up, and quit Xcode.
delete the cache Run "rm -rf ~/Library/Developer/Xcode/DerivedData" in terminal
open the project and re-build it

**Comment by maartenheideman** [comment]
That's not solving the issue. Same errors appear on building

**Comment by mostafa-mansour1** [comment]
kindly send the output of 
```
ionic info
```

**Comment by mostafa-mansour1** [comment]
can u link the CoreServices.framework to your project?


![image](https://user-images.githubusercontent.com/6575879/107872205-e2ef2900-6ec1-11eb-8246-dc923edf4aa5.png)


![image](https://user-images.githubusercontent.com/6575879/107872209-e7b3dd00-6ec1-11eb-9fd8-4eb9dffeb445.png)

**Comment by maartenheideman** [comment]
> kindly send the output of
> 
> ```
> ionic info
> ```
```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 5.2.3
   @angular-devkit/build-angular : 0.1100.2
   @angular-devkit/schematics    : 9.1.11
   @angular/cli                  : 10.0.8
   @ionic/angular-toolkit        : 2.3.0

Capacitor:

   capacitor (Capacitor CLI) : 2.4.2
   @capacitor/core           : 2.4.2

System:

   NodeJS : v10.15.3 (/usr/local/bin/node)
   npm    : 6.14.4
   OS     : macOS
```

**Comment by maartenheideman** [comment]
`can u link the CoreServices.framework to your project?` this doesn't fix the problem.

**Comment by mostafa-mansour1** [comment]
try link the framework here also 

![image](https://user-images.githubusercontent.com/6575879/107876489-b813cd80-6edf-11eb-9e28-46f7973c7b2e.png)


if it not working, kindly send in private your ios folder mostafa@outlook.kr

**Comment by mostafa-mansour1** [comment]
thanks for sharing the ios folder with me 

I found the solution 

just apply the following steps, and it will build successfully 

![image](https://user-images.githubusercontent.com/6575879/107923285-b2bf8d00-6f8a-11eb-8249-d9169c99d5f3.png)

**Comment by maartenheideman** [comment]
Thanx for the reply! Your suggestion works and fixes the issue! 

Maybe for a next release.. every time on running `npx cap sync` you have to re add 'CoreServices.framework' to the Pods, shouldn't that go automatically?

**Comment by mostafa-mansour1** [comment]
i will check how to do that, and will update the plugin

**Comment by mostafa-mansour1** [comment]
kindly check the plugin in this branch 
if it works I will merge it to master 

```
https://github.com/mostafa-mansour1/previewAnyFile.git#fix_ios_framework
```

I have no idea how to add Cordova plugin from branches in the capacitor, 
if u cannot add from a branch, you can download the branch and add it manually 


**waiting for your confirmation**

**Comment by maartenheideman** [comment]
I'll tried and build succeeded even after `npx cap sync` so great work!
