### ISSUE TITLE
ios build issues... 

### ISSUE THREAD

**Issue by muthukumarpsl** [mostafa-mansour1/previewAnyFile#19]
.....Plugins/cordova-plugin-preview-any-file/PreviewAnyFile.swift:3:48: error: cannot find type 'CDVPlugin' in scope
@objc(HWPPreviewAnyFile) class PreviewAnyFile: CDVPlugin {
                                               ^~~~~~~~~
...../Plugins/cordova-plugin-preview-any-file/PreviewAnyFile.swift:7:28: error: cannot find type 'CDVInvokedUrlCommand' in scope
    func preview(_command: CDVInvokedUrlCommand){
                           ^~~~~~~~~~~~~~~~~~~~
.../Plugins/cordova-plugin-preview-any-file/PreviewAnyFile.swift:3:2: error: only classes that inherit from NSObject can be declared @objc
@objc(HWPPreviewAnyFile) class PreviewAnyFile: CDVPlugin {
~^~~~~~~~~~~~~~~~~~~~~~~~
.../Plugins/cordova-plugin-preview-any-file/PreviewAnyFile.swift:106:1: error: cannot declare conformance to 'NSObjectProtocol' in Swift; 'PreviewAnyFile' should inherit 'NSObject' instead
extension PreviewAnyFile: QLPreviewControllerDataSource, QLPreviewControllerDelegate {
^
.../Plugins/cordova-plugin-preview-any-file/PreviewAnyFile.swift:106:1: note: do you want to add protocol stubs?
extension PreviewAnyFile: QLPreviewControllerDataSource, QLPreviewControllerDelegate {
^
.../Plugins/cordova-plugin-preview-any-file/PreviewAnyFile.swift:9:28: error: cannot find 'CDVPluginResult' in scope
        var pluginResult = CDVPluginResult(
                           ^~~~~~~~~~~~~~~
/Users/psluser/Desktop/serviceon_code/serviceon_customer/ServiceOn_CustApp/platforms/ios/Serviceon/Plugins/cordova-plugin-preview-any-file/PreviewAnyFile.swift:10:21: error: cannot find 'CDVCommandStatus_ERROR' in scope
            status: CDVCommandStatus_ERROR
                    ^~~~~~~~~~~~~~~~~~~~~~
/Users/psluser/Desktop/serviceon_code/serviceon_customer/ServiceOn_CustApp/platforms/ios/Serviceon/Plugins/cordova-plugin-preview-any-file/PreviewAnyFile.swift:100:28: error: cannot find 'CDVPluginResult' in scope
        let pluginResult = CDVPluginResult(status: CDVCommandStatus_OK, messageAs: "CLOSING");
                           ^~~~~~~~~~~~~~~
/Users/psluser/Desktop/serviceon_code/serviceon_customer/ServiceOn_CustApp/platforms/ios/Serviceon/Plugins/cordova-plugin-preview-any-file/PreviewAnyFile.swift:100:52: error: cannot find 'CDVCommandStatus_OK' in scope
        let pluginResult = CDVPluginResult(status: CDVCommandStatus_OK, messageAs: "CLOSING");
                                                   ^~~~~~~~~~~~~~~~~~~

warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'OneSignal' from project 'Pods')
warning: AddressBook is deprecated. Consider migrating to Contacts instead. (in target 'Serviceon' from project 'Serviceon')
** BUILD FAILED **

``
``
``
``
``
**`in ios folder has only .swift file   but xcode required the .m file`**

**Comment by mostafa-mansour1** [comment]
Kindly totally remove the plugin then build the app then add it again


Regards,
___________________________
Mostafa Mansour
Software Engineer
00971 524988466
0020 1113019196

On 11 Mar 2021, at 2:27 PM, muthukumarpsl ***@***.***> wrote:

﻿

.....Plugins/cordova-plugin-preview-any-file/PreviewAnyFile.swift:3:48: error: cannot find type 'CDVPlugin' in scope
@objc<https://github.com/objc>(HWPPreviewAnyFile) class PreviewAnyFile: CDVPlugin {
^~~~~~~~~
...../Plugins/cordova-plugin-preview-any-file/PreviewAnyFile.swift:7:28: error: cannot find type 'CDVInvokedUrlCommand' in scope
func preview(_command: CDVInvokedUrlCommand){
^~~~~~~~~~~~~~~~~~~~
.../Plugins/cordova-plugin-preview-any-file/PreviewAnyFile.swift:3:2: error: only classes that inherit from NSObject can be declared @objc<https://github.com/objc>
@objc<https://github.com/objc>(HWPPreviewAnyFile) class PreviewAnyFile: CDVPlugin {
~^~~~~~~~~~~~~~~~~~~~~~~~
.../Plugins/cordova-plugin-preview-any-file/PreviewAnyFile.swift:106:1: error: cannot declare conformance to 'NSObjectProtocol' in Swift; 'PreviewAnyFile' should inherit 'NSObject' instead
extension PreviewAnyFile: QLPreviewControllerDataSource, QLPreviewControllerDelegate {
^
.../Plugins/cordova-plugin-preview-any-file/PreviewAnyFile.swift:106:1: note: do you want to add protocol stubs?
extension PreviewAnyFile: QLPreviewControllerDataSource, QLPreviewControllerDelegate {
^
.../Plugins/cordova-plugin-preview-any-file/PreviewAnyFile.swift:9:28: error: cannot find 'CDVPluginResult' in scope
var pluginResult = CDVPluginResult(
^~~~~~~~~~~~~~~
/Users/psluser/Desktop/serviceon_code/serviceon_customer/ServiceOn_CustApp/platforms/ios/Serviceon/Plugins/cordova-plugin-preview-any-file/PreviewAnyFile.swift:10:21: error: cannot find 'CDVCommandStatus_ERROR' in scope
status: CDVCommandStatus_ERROR
^~~~~~~~~~~~~~~~~~~~~~
/Users/psluser/Desktop/serviceon_code/serviceon_customer/ServiceOn_CustApp/platforms/ios/Serviceon/Plugins/cordova-plugin-preview-any-file/PreviewAnyFile.swift💯28: error: cannot find 'CDVPluginResult' in scope
let pluginResult = CDVPluginResult(status: CDVCommandStatus_OK, messageAs: "CLOSING");
^~~~~~~~~~~~~~~
/Users/psluser/Desktop/serviceon_code/serviceon_customer/ServiceOn_CustApp/platforms/ios/Serviceon/Plugins/cordova-plugin-preview-any-file/PreviewAnyFile.swift💯52: error: cannot find 'CDVCommandStatus_OK' in scope
let pluginResult = CDVPluginResult(status: CDVCommandStatus_OK, messageAs: "CLOSING");
^~~~~~~~~~~~~~~~~~~

warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.3.99. (in target 'OneSignal' from project 'Pods')
warning: AddressBook is deprecated. Consider migrating to Contacts instead. (in target 'Serviceon' from project 'Serviceon')
** BUILD FAILED **

in ios folder has only .swift file but xcode required the .m file
