### ISSUE TITLE
Share button and done button

### ISSUE THREAD

**Issue by mikeschoneveld** [mostafa-mansour1/previewAnyFile#2]
Is it possible to remove the share button and translate the 'done' button?

**Comment by mostafa-mansour1** [comment]
You are talking about ios or android to check the Ability

**Comment by mikeschoneveld** [comment]
Hi, I'm talking about the share button in iOS 

![image](https://user-images.githubusercontent.com/36042966/68868861-8c140600-06f8-11ea-95e7-bd3d64302245.png)

I don't wan't the user to be able to download the files on their phone.

**Comment by mostafa-mansour1** [comment]
Will check and reply back to you


Regards,
___________________________
Mostafa Mansour
Software Engineer
00971 524988466
0020 1113019196

On 14 Nov 2019, at 7:05 PM, Mike Schoneveld <notifications@github.com> wrote:

﻿

Hi, I'm talking about the share button in iOS

[image]<https://user-images.githubusercontent.com/36042966/68868861-8c140600-06f8-11ea-95e7-bd3d64302245.png>

I don't wan't the user to be able to download the files on their phone.

**Comment by mikeschoneveld** [comment]
> Will check and reply back to you Regards,

Do you have any update on this?

**Comment by mostafa-mansour1** [comment]
Yes it can remove share
Will add update within 2 days


Regards,
___________________________
Mostafa Mansour
Software Engineer
00971 524988466
0020 1113019196

On 22 Nov 2019, at 1:46 AM, Mike Schoneveld <notifications@github.com> wrote:

﻿

Will check and reply back to you Regards,

Do you have any update on this?

**Comment by Benneee** [comment]
Hi @mostafa-mansour1 ... Thank you for this plugin.

However, is there any update as regards this issue? Thanks

**Comment by mostafa-mansour1** [comment]
I tried by with no hope, we can make it in future
