### ISSUE TITLE
PreviewAnyFile.swift:271: Fatal error: Unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by Siedlerchr** [mostafa-mansour1/previewAnyFile#23]
I encountered this problem and after debugging I found out it happens when the url to open (myUrl) contains spaces.

Actually, the following lines can be removed because you already initialize itemUrl in the lines before. 

https://github.com/mostafa-mansour1/previewAnyFile/blob/b6c4fd6fb51fcca4aefa6f3c0737a0dcb980b54f/src/ios/PreviewAnyFile.swift#L267-L269

**Comment by mostafa-mansour1** [comment]
i merged it

**Comment by mostafa-mansour1** [comment]
npm has been updated as well https://www.npmjs.com/package/cordova-plugin-preview-any-file
