### ISSUE TITLE
Unable to view file stored at Azure Storage Explorer

### ISSUE THREAD

**Issue by FrostyMint** [mostafa-mansour1/previewAnyFile#29]
Hi I having trouble to preview file such as image and pdf using url from azure storage explorer that also contain with the SaS token, before that i did try using inAppBrowser which i able to view those file without problem. I did aso tested out using sample image from google which able to view the image using this previewAnyFile. Below attached image are the output i get after i launch the function Thanks.
![image](https://user-images.githubusercontent.com/86829786/124256378-cd6f5880-db5d-11eb-9d4e-4f0be7f3cc3c.png)
![image](https://user-images.githubusercontent.com/86829786/124256392-d102df80-db5d-11eb-9100-bfa50ed8702a.png)
```
   // jpgUrl = 'https://........blob.core.windows.net/...../Andy.jpg?sp=.......(SaStoken)';
  openImage(){
    this.previewAnyFile.preview(this.jpgUrl).then(()=>{

    },(err)=>{
      alert(JSON.stringify(err));
    })

  }
```

**Comment by mostafa-mansour1** [comment]
You have to append the file name in the last of the URL or to pass the options 

I need from you to use the direct Cordova plugin not ionic native, because it has an issues until they process my last pull request 

use this code 

```
 (<any>window).PreviewAnyFile.previewPath(
        win => console.log("open status",win),
        error => console.error("open failed", error),
        this.jpgUrl,{name : "Andy.jpg"}
    );
```

**Comment by FrostyMint** [comment]
@mostafa-mansour1 Alright, Thanks for the suggestion!
