### ISSUE TITLE
Not able to see files on iOS, It shows just a grey screen with the file name on it.

### ISSUE THREAD

**Issue by BhavinHoum** [mostafa-mansour1/previewAnyFile#31]
![9dNYF](https://user-images.githubusercontent.com/75417017/126774138-fa406f19-42d6-4add-a777-3ca455580520.png)

**Comment by mostafa-mansour1** [comment]
Hi,

You have to use the name param or extension
Because Now the preview doesn’t know the file type

‘’’


window.PreviewAnyFile.previewPath(
        win => console.log("open status",win),
        error => console.error("open failed", error),
        "http://www.domain.com/samplefile",{name : file.pdf}
    );

‘’’

Regards,
___________________________
Mostafa Mansour
Software Engineer
00971 524988466
0020 1113019196

On 23 Jul 2021, at 1:12 PM, Bhavin Vadhiya ***@***.***> wrote:

﻿

**Comment by HenokG** [comment]
I'm also facing the same issue, tried it with both `name` and `mimeType` but i still face this issue

`          window.PreviewAnyFile.previewPath(
              win => console.log("open status",win),
              error => console.error("open failed", error),
              $scope.document.url, {mimeType:'application/pdf', name: $scope.document.fileName}
          );`

if it makes any difference, the url is from an S3 bucket and i'm testing this on emulator

**Comment by mostafa-mansour1** [comment]
you are sure that name: $scope.document.fileName has the .pdf in the last?

**Comment by HenokG** [comment]
this [soln](https://stackoverflow.com/a/64693234/4650095) helped me, i was using an encoded URL, i had to just update it to `decodeURIComponent($scope.document.url)`

**Comment by mostafa-mansour1** [comment]
thanks for sharing the solution with me
