### ISSUE TITLE
Callback on clicking Done

### ISSUE THREAD

**Issue by drewwynne0** [mostafa-mansour1/previewAnyFile#5]
Is it possible to add a callback when clicking Done?  This will help when needing to navigate the user to alternate views and trigger response messages

**Comment by mostafa-mansour1** [comment]
I will try to do that, let me check


Regards,
___________________________
Mostafa Mansour
Software Engineer
00971 524988466
0020 1113019196

On 29 May 2020, at 11:10 PM, drewwynne0 <notifications@github.com> wrote:

﻿

Is it possible to add a callback when clicking Done? This will help when needing to navigate the user to alternate views and trigger response messages

**Comment by drewwynne0** [comment]
@mostafa-mansour1 sorry didn't look at my message, just created one for iOS and created a pull request.  Hope this works for how you want it?

**Comment by mostafa-mansour1** [comment]
Thanks for your help , 
Can you update read me so i can merge the pull request
