### ISSUE TITLE
why download pdf not  view?

### ISSUE THREAD

**Issue by coolara** [mostafa-mansour1/previewAnyFile#7]
hello this is my code
` const viewUrl = 'http://www.africau.edu/images/default/sample.pdf';
    this.previewAnyFile.preview(viewUrl).then(resp => {
      console.log(resp);
    }, err => {
      console.log(err);
    });`
on android device it download file not view why?

**Comment by mostafa-mansour1** [comment]
The file must be downloaded to user device to preview it with local application


Regards,
___________________________
Mostafa Mansour
Software Engineer
00971 524988466
0020 1113019196

On 24 Jun 2020, at 5:55 AM, wzy <notifications@github.com> wrote:

﻿

hello this is my code
const viewUrl = 'http://www.africau.edu/images/default/sample.pdf'; this.previewAnyFile.preview(viewUrl).then(resp => { console.log(resp); }, err => { console.log(err); });
on android device it download file not view why?

**Comment by coolara** [comment]
thank u; download is not a better way  i need online preview
