### ISSUE TITLE
Obejct is not function 

### ISSUE THREAD

**Issue by hanaafiqp** [mostafa-mansour1/previewAnyFile#8]
why when i am add this plugin to my ionic 3 projects, and even i am finished build/compile my project. Then when i want use it. Its show error like this. 
`ERROR TypeError: Object(...) is not a function
    at e.preview (vendor.js:1)
    at l.download (main.js:1)
    at Object.handleEvent (0.js:1)
    at Object.handleEvent (vendor.js:1)
    at Object.handleEvent (vendor.js:1)
    at Ut (vendor.js:1)
    at vendor.js:1
    at HTMLElement.<anonymous> (vendor.js:1)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (vendor.js:1)`

Thats my code, 

`me.previewFile.preview("file:///storage/emulated/0/MyRadiant/Form_Pengkinian_Data_(Individual)_(2).pdf")
        .then((res: any) => console.log(res))
        .catch((error: any) => console.error("eror hehe",error));`

**Comment by mostafa-mansour1** [comment]
Kindly share the full file code


Regards,
___________________________
Mostafa Mansour
Software Engineer
00971 524988466
0020 1113019196

On 24 Jun 2020, at 2:34 PM, hanaafiqp <notifications@github.com> wrote:

﻿

why when i am add this plugin to my ionic 3 projects, and even i am finished build/compile my project. Then when i want use it. Its show error like this.
ERROR TypeError: Object(...) is not a function at e.preview (vendor.js:1) at l.download (main.js:1) at Object.handleEvent (0.js:1) at Object.handleEvent (vendor.js:1) at Object.handleEvent (vendor.js:1) at Ut (vendor.js:1) at vendor.js:1 at HTMLElement.<anonymous> (vendor.js:1) at t.invokeTask (polyfills.js:3) at Object.onInvokeTask (vendor.js:1)

Thats my code,

me.previewFile.preview("file:///storage/emulated/0/MyRadiant/Form_Pengkinian_Data_(Individual)_(2).pdf") .then((res: any) => console.log(res)) .catch((error: any) => console.error("eror hehe",error));
